language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"

script:
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - pip freeze

deploy:
  provider: script
  script: make publish
  on:
    tags: true
